#!/usr/bin/env bash

# Outputs vim history files under the current directory
# Usage:
#   voxide-vim-history-files # choose from history files in current dir
#   voxide-vim-history-files ~ # choose from history files in ~
#   voxide-vim-history-files dir regex # choose from dir, prefilter with regex

if [[ -n "$1"  && -d "$1" ]]; then
  dir="$1/"
  shift
else
  dir=""
fi

ag="${1:-.}"

nvim --headless -c "redir! > /dev/stdout | silent oldfiles | qall!" | \
  sed 's/^[0-9]*: //' | \
  sed -r 's/^\s+//' | \
  sed -r 's/\s+$//' | \
  grep --color=auto . | \
  grep --color=auto ^"$(git rev-parse --show-toplevel 2>/dev/null || pwd -P)"/ | \
  sed s@$(pwd -P)/@@ | \
  grep --color=auto -v COMMIT_EDITMSG | \
  ag "$ag" | \
  { while IFS= read -r f; do test -e "$f" && printf "%s\n" "$dir$f"; done; }

